### ISSUE TITLE
RuntimeError: CUDA out of memory. happend in train.py#cal_loss#

### ISSUE THREAD

**Issue by huangxianliang** [jadore801120/attention-is-all-you-need-pytorch#103]
there is a memory problem in train.py#cal_loss# with batce_size is 128.
code:one_hot = one_hot * (1 - eps) + (1 - one_hot) * eps / (n_class - 1)
please help me,thanks.

**Comment by Elenore1997** [comment]
I have met `CUDA error: out of memory` too, even though I decreased the batch_size to 32. I think the training process with cuda have some little bugs and I cannot figure it out.

**Comment by jadore801120** [comment]
@huangxianliang @Elenore1997 
Please take a look on the newest code.
I tried to reduce all the `contiguous` operations and temporary variables as possible.
But for me, batch size 256 is the limit. (the paper used 2048, which is crazy.)
Hope it helps.
