### ISSUE TITLE
normalize between sub-modules

### ISSUE THREAD

**Issue by andrster1** [jadore801120/attention-is-all-you-need-pytorch#105]
Hi do you normalize the outputs of the multyhead attention at encoder side and the outputs of self attentional multyhead attention, encoder-decoder multyhead attention at decoder side, as the paper dictates or just at the corresponding feed forward of each sublayer?

**Comment by jadore801120** [comment]
Hello @andrster1 ,
The layer norm is applied in following conditions.
- After the embedding
- After the multi-head attn
- After the position-wise feed forward
Please take a look on the newest code.
Hope this helps.
