### ISSUE TITLE
is n_class == vocabulary size an inferred size and not true size?

### ISSUE THREAD

**Issue by rush86999** [jadore801120/attention-is-all-you-need-pytorch#108]
as per the code 
```
n_class = pred.size(1)
```
but pred.size(1) is actually the maximum sequence length and not the vocabulary size. Is this value inferred for calculating loss?

**Comment by jadore801120** [comment]
Hi @rush86999 
In fact, after the decoding, I reshape the prediction in a 2-d matrix.
The first is the batch size times sequence length, and the second is the vocabulary size.
Hope this helps.
