### ISSUE TITLE
When I try to train without teacher forcing, CUDA out of memory.

### ISSUE THREAD

**Issue by newcolour1994** [jadore801120/attention-is-all-you-need-pytorch#111]
I try to modify the code in "train.py" to train without teacher forcing. But I meet CUDA out of memory error. I use the same code in inference phase is ok. So what is going wrong?

**Comment by whxf** [comment]
I meet the same problem, have you solved it?

**Comment by jonathanking** [comment]
@whxf @ZhaoXiny  I'm curious, can you share how you are training without teacher forcing? I am trying to implement the same thing. Thanks.

**Comment by jadore801120** [comment]
Dear all,
I modified the code to reduce the `contiguous` operations as possible and avoiding using temporary variables.
Please take a look on the newest code.
Hope it helps.
