### ISSUE TITLE
How can I get the word embedding from Transformer

### ISSUE THREAD

**Issue by sumhncku** [jadore801120/attention-is-all-you-need-pytorch#112]
Hi,
I need the word embedding of Transformer,
but I donot know how to get word embedding.
Can anyone help me?
Thanks

**Comment by jadore801120** [comment]
Sure, the weight we save at every epoch contains the word embedding weights.
Starting with `checkpoint = torch.load('your_saved_model.pt')`, and you could find the key corresponding to the target embedding weight in the `checkpoint`.
