### ISSUE TITLE
A cause of "CUDA out of memory" problem

### ISSUE THREAD

**Issue by whxf** [jadore801120/attention-is-all-you-need-pytorch#114]
I have met `RuntimeError: CUDA out of memory. `  problem. And I found solution in  [GPU is not utilized while occur RuntimeError: cuda runtime error: out of memory at](https://discuss.pytorch.org/t/gpu-is-not-utilized-while-occur-runtimeerror-cuda-runtime-error-out-of-memory-at/34780).

> albanD said: 
> Hi,
> Tensorflow has the bad habbit of taking all the memory on the device and prevent anything from happening on it as anything will OOM.
> There was a small bug in pytorch that was initializing the cuda runtime on device 0 when printing that has been fixed.
> A simple workaround is to use CUDA_VISIBLE_DEVICES=2. This will hide all devices but the one you specify and will make sure you never use other devices.

**Comment by jadore801120** [comment]
Dear @whxf 
Please take a look on the newest code. 
I try to reduce as many the `contiguous` operations as possible with broadcasting.
Hope it helps.
