### ISSUE TITLE
UnicodeDecodeError: 'ascii' codec can't decode

### ISSUE THREAD

**Issue by hqlin2018** [jadore801120/attention-is-all-you-need-pytorch#122]
when i run # python preprocess.py -train_src data/multi30k/train.en.atok -train_tgt data/multi30k/train.de.atok -valid_src data/multi30k/val.en.atok -valid_tgt data/multi30k/val.de.atok -save_data data/multi30k.atok.low.pt 
it traceback 
[Info] Get 28993 instances from data/multi30k/train.en.atok
Traceback (most recent call last):
  File "preprocess.py", line 164, in <module>
    main()
  File "preprocess.py", line 90, in main
    opt.train_tgt, opt.max_word_seq_len, opt.keep_case)
  File "preprocess.py", line 12, in read_instances_from_file
    for sent in f:
  File "/root/miniconda3/envs/Lin/lib/python3.6/encodings/ascii.py", line 26, in decode
    return codecs.ascii_decode(input, self.errors)[0]
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 14: ordinal not in range(128)

**Comment by hqlin2018** [comment]
I solved the problem by add  encoding='UTF-8' in preprocess.py line 11, 
 as open(inst_file, encoding='UTF-8')

**Comment by jadore801120** [comment]
@hqlin2018 Thanks for the report!
