### ISSUE TITLE
Question about  get_the_best_score_and_idx in Beam.py

### ISSUE THREAD

**Issue by yudmoe** [jadore801120/attention-is-all-you-need-pytorch#125]
![TIM截图20190929013809](https://user-images.githubusercontent.com/39221113/65820322-fca2b880-e259-11e9-9c28-9f6f1bcd2979.png)
since you want the best score,why do you selcet the second?

**Comment by jadore801120** [comment]
Sorry for the confusion, I made the beam search now more concise.
Please take a look, Thanks.
