### ISSUE TITLE
 AttributeError: 'Decoder' object has no attribute 'tgt_word_emb'

### ISSUE THREAD

**Issue by HassanNaeemjutt** [jadore801120/attention-is-all-you-need-pytorch#128]
I use python 3.7 when I run pythhon train.py I face this problem
  type(self).__name__, name)) AttributeError: 'Decoder' object has no attribute 'tgt_word_emb'
if tgt_emb_prj_weight_sharing:
           
            self.tgt_word_prj.weight = self.decoder.tgt_word_emb.weight
            self.x_logit_scale = (d_model ** -0.5)  # scaling trick
        else:
            self.x_logit_scale = 1.  # no scaling trick

        if emb_src_tgt_weight_sharing:
       
            assert n_src_vocab == n_tgt_vocab  # ensure same vocab size of src/ tgt
            self.encoder.src_word_emb.weight = self.decoder.tgt_word_emb.weight

**Comment by jadore801120** [comment]
Sorry for your confusion, I guess there was an typo.
Please check the newest code. 
Hope this helps
