### ISSUE TITLE
What I get from the default is very different from what you showed. Is it because of the code update?

### ISSUE THREAD

**Issue by SmallSmallQiu** [jadore801120/attention-is-all-you-need-pytorch#132]
![image](https://user-images.githubusercontent.com/44115671/70972490-6a82b180-20de-11ea-8e4a-4e8dbe7403fc.png)
![image](https://user-images.githubusercontent.com/44115671/70972437-5b036880-20de-11ea-81aa-729ad3b20e98.png)
![1 jpg](https://user-images.githubusercontent.com/44115671/70973031-c568d880-20df-11ea-9c1d-4bac10d7f000.png)

**Comment by SmallSmallQiu** [comment]
I didn't get a good model

**Comment by jadore801120** [comment]
i am sorry, I do not mean that the epoch setting is the best.
The model is not yet converged after 10 epoch. You could try with 300 epochs.

**Comment by SmallSmallQiu** [comment]
> i am sorry, I do not mean that the epoch setting is the best.
> The model is not yet converged after 10 epoch. You could try with 300 epochs.

![image](https://user-images.githubusercontent.com/44115671/70974033-d61a4e00-20e1-11ea-97bd-512b942604fa.png)
I have tried to increase the value of echop to 100, but the system reported CUDA error, your echop parameter seems to affect the CUDA occupation size, my GPU is 1080

**Comment by jadore801120** [comment]
In this case, you have to reduce the size of your batch.

**Comment by SmallSmallQiu** [comment]
> 在这种情况下，您必须减小批次的大小。

The effect of the model has been greatly improved. Thank you for your help

**Comment by jadore801120** [comment]
No problem, feel free to open another issue if there is anything wrong.
Best, 
Yu-Hsiang
