### ISSUE TITLE
why use matmul to instead of bmm?

### ISSUE THREAD

**Issue by kaituoxu** [jadore801120/attention-is-all-you-need-pytorch#137]
As title says.

Does contiguous operations spend a lot of time?

https://github.com/jadore801120/attention-is-all-you-need-pytorch/commit/e2c95f83907f4ee480eef074822471b4844f498c#diff-8f6e8c7df2646b52504a8ddccab50f6e

Thx.

**Comment by jadore801120** [comment]
Dear @kaituoxu 
I did not make a careful test on the time spending resulted from the contiguous op.
However, according to https://discuss.pytorch.org/t/contigious-vs-non-contigious-tensor/30107/2 ,
I believe it will be better to avoid using contiguous for memory efficiency.
On the other hand, using matmul could avoid complicated transposing which I believe it will be easier to understand.
Hope this helps.
Yu-Hsiang

**Comment by kaituoxu** [comment]
Thanks!
