### ISSUE TITLE
How to export the trained chkpt network to onnx?

### ISSUE THREAD

**Issue by ZhangDongyuCN** [jadore801120/attention-is-all-you-need-pytorch#172]
I have trained a network and now need to turn it into an ONNX inference model. What should I do? If anyone knows, please help me, thanks.

**Comment by 506610466** [comment]
$  python translate.py -data_pkl m30k_deen_shr.pkl -model ./output/model.chkpt -output prediction.txt

**Comment by shell-nlp** [comment]
> I have trained a network and now need to turn it into an ONNX inference model. What should I do? If anyone knows, please help me, thanks.
 python translate.py -data_pkl m30k_deen_shr.pkl -model ./output/model.chkpt -output prediction.txt 
是这样吗？

**Comment by ZhangDongyuCN** [comment]
> > I have trained a network and now need to turn it into an ONNX inference model. What should I do? If anyone knows, please help me, thanks.
> > python translate.py -data_pkl m30k_deen_shr.pkl -model ./output/model.chkpt -output prediction.txt
> > 是这样吗？

这个是加载训练好的网络进行测试和验证，并不是把model.chkpt导出到onnx格式

**Comment by warren-wzw** [comment]
你好，请问解决了吗？

**Comment by ZhangDongyuCN** [comment]
没有搞定，现在换工作了，已经换公司不搞这个了。来自：张东宇在 2023年5月8日，10:49，warren ***@***.***> 写道：﻿
你好，请问解决了吗？

**Comment by warren-wzw** [comment]
好的 谢谢
