### ISSUE TITLE
Ubuntu Server Unable to recognise German Character

### ISSUE THREAD

**Issue by gaopeng-eugene** [jadore801120/attention-is-all-you-need-pytorch#18]
Ubuntu Server : Ein Boston Terrier läuft über saftig-grünes Gras vor einem wei?^?en Zaun.

Macbook Pro : Ein Boston Terrier läuft über saftig-grünes Gras vor einem weißen Zaun.

Can you tell me how to set up the language encoding in Ubuntu? Best Wishes

**Comment by jadore801120** [comment]
Hi @gaopeng-eugene,
Sorry for the late reply! but I am not familiar with Ubuntu language encoding ... 
Did you solve your problem?
Yu-Hsiang
