### ISSUE TITLE
What is the score in beam search stands for?

### ISSUE THREAD

**Issue by XinyuZhou-1014** [jadore801120/attention-is-all-you-need-pytorch#20]
I notice there's a score during beam search. But the meaning of it is very ambiguous and hard to be understood. Is there any intuitive description for it?

**Comment by jadore801120** [comment]
Hi @XinyuZhou-1014 ,
Sorry for the confusion.
The [scores](https://github.com/jadore801120/attention-is-all-you-need-pytorch/blob/master/transformer/Beam.py#L23) stand for the total probability for the generated sequences so far.
Hope this helps.

Yu-Hsiang

**Comment by XinyuZhou-1014** [comment]
@jadore801120 Thanks for the description!

I noticed a small issue that, in train.py, you seems to use [padded sequence](https://github.com/jadore801120/attention-is-all-you-need-pytorch/blob/master/train.py#L66) to calculate the final accuracy, does it should only counts number of words in the target sequence?

**Comment by jadore801120** [comment]
Hi @XinyuZhou-1014 
Thanks for pointing out! I think your suggestion may be right.
I will try to calculate the accuracy on the original sequence.
Yu-Hsiang
