### ISSUE TITLE
d_word_vec and d_model must be equal in Encoder

### ISSUE THREAD

**Issue by yangkky** [jadore801120/attention-is-all-you-need-pytorch#23]
According to the paper, d_word_vec and d_model must be equal. However, the interface for Encoder allows you to set them to different values. If you initialize an Encoder and set them to different values, you get an error in Line 54 MultiHeadAttention during the forward pass.

**Comment by jadore801120** [comment]
Hi @yangkky ,
I think you are right. I will fix it.
Thanks!

Yu-Hsiang

**Comment by jadore801120** [comment]
Hi @yangkky,

Unfortunately, I found that there may not be a simple and proper way to set up the different dimensions but to follow the setting of the original paper.
Therefore, I remove the option to set up the dimension of the word embedding in [4f4a192](https://github.com/jadore801120/attention-is-all-you-need-pytorch/commit/4f4a192f0fd272102c8852b00b1007dffd292b90).
Thanks for your report!

Yu-Hsiang
