### ISSUE TITLE
need to check

### ISSUE THREAD

**Issue by jiahuigeng** [jadore801120/attention-is-all-you-need-pytorch#26]
if the source target numbers are correct

**Comment by jadore801120** [comment]
Hi @jiahuigeng,
Would you mind to talk more about it?
Thanks!

Yu-Hsiang

**Comment by jadore801120** [comment]
Hi @jiahuigeng,
I guess you are talking about the enc/dec with different number of layers?
In this case, the problem is solved with 07e2cda7d6e3ed9225ae1063b90a077432c24995.
Please take a look. 
Thanks!
