### ISSUE TITLE
Feeding the output of the last encoding layer to the decoder

### ISSUE THREAD

**Issue by Yevgnen** [jadore801120/attention-is-all-you-need-pytorch#27]
The original paper and the animation in [this page](https://research.googleblog.com/2017/08/transformer-novel-neural-network.html) seem only feed the output of the *last* encoding layer to the decoder, while the implementation [here](https://github.com/jadore801120/attention-is-all-you-need-pytorch/blob/master/transformer/Models.py#L122) seems feed the output of *each* encoding layer to the corresponding decoding layer, which might not work if the encoder and the decoder have different number of layers.

**Comment by jadore801120** [comment]
Hi @Yevgnen,
I didn't know that there is such an animation before!
I will modify it to make it behave the same as the original paper.
Thank you so much!

**Comment by jadore801120** [comment]
Hi @Yevgnen,
I have modified the model to take only the last encoder layer output for the decoding.
Please check 07e2cda7d6e3ed9225ae1063b90a077432c24995.
Besides, by modifying the model, the memory issue is also slightly mitigated.
Thanks for your kind reminder!

Yu-Hsiang
