### ISSUE TITLE
how to change size of dictionaries

### ISSUE THREAD

**Issue by cong1** [jadore801120/attention-is-all-you-need-pytorch#31]
how to change size of dictionaries? I use a new corpus,but its dictionary is ao big. I don not know how to change it.

**Comment by jadore801120** [comment]
Hello @cong1 sorry for the late reply. 
I am not sure about your question. Maybe you should ignore case and set a higher word ocurrence count threshold to filter out the low-frequency word?
Hope you already fix it.
Best,
Yu-Hsiang
