### ISSUE TITLE
Positional Encoding

### ISSUE THREAD

**Issue by jasonleeinf** [jadore801120/attention-is-all-you-need-pytorch#32]
In `position_encoding_init`, shouldn't it be

``
[pos / np.power(10000, (i//2)*2 / d_pos_vec ) for i in range(d_pos_vec)]
``

instead of 

``
[pos / np.power(10000, 2*i/d_pos_vec) for i in range(d_pos_vec)]
``

In the original formulation, for positions `2i` and `2i+1`, the power should be `2i / d_model`.

**Comment by jadore801120** [comment]
Hi @jasonleeinf 

Thank you so much to point out this mistake!
This part has been fixed in 7fa8c63. Please take a look.
Thanks!

Yu-Hsiang
