### ISSUE TITLE
Multi-GPUs?

### ISSUE THREAD

**Issue by ayanamongol** [jadore801120/attention-is-all-you-need-pytorch#34]
Hi, thanks for the sharing.
It seems like this code does not support multi-GPUs.
So are you planning on it?

**Comment by jadore801120** [comment]
Hi @ayanamongol 

Thanks for your comment!
Unfortunately, I don't have multi-GPUs device to test.
I would love to try if I have the machine!

Yu-Hsiang

**Comment by ayanamongol** [comment]
Well, Thanks for the response anyway ~:)
