### ISSUE TITLE
What command can continue running program?

### ISSUE THREAD

**Issue by cong1** [jadore801120/attention-is-all-you-need-pytorch#35]
Hi,thanks for your sharing.
My program has broken down。
What command can continue running program at GPU?

CUDA_VISIBLE_DEVICES=3 python train.py -data data/multi30k.atok.low.pt -save_model trained -save_mode best -proj_share_weight

**Comment by jadore801120** [comment]
You can follow the translate.py to load a trained model weight.
Hope this helps
