### ISSUE TITLE
Document strings' style do not accord PEP8

### ISSUE THREAD

**Issue by ghrua** [jadore801120/attention-is-all-you-need-pytorch#37]
As mentioned [here](https://www.python.org/dev/peps/pep-0008/#documentation-strings):
> PEP 257 describes good docstring conventions. Note that most importantly, the """ that ends a multiline docstring should be on a line by itself, e.g.:
>
> """Return a foobang
>
> Optional plotz says to frobnicate the bizbaz first.
"""
> For one liner docstrings, please keep the closing """ on the same line.

but most docstrings used in the code is:
```
''' document strings '''
```

**Comment by jadore801120** [comment]
Hello @ghrua , thanks for the notice. I spend most of time to tune the code and had less notice on styling my comment. Will fix this if I have time. 
Thanks,
Yu-Hsiang
