### ISSUE TITLE
Preprocessing Error

### ISSUE THREAD

**Issue by karanchahal** [jadore801120/attention-is-all-you-need-pytorch#41]
On running the following command for preprocessing
`for l in en de; do for f in data/multi30k/*.$l; do if [[ "$f" != *"test"* ]]; then sed -i "$ d" $f; fi;  done; done;
`
I'm getting the following error
`sed: 1: "data/multi30k/train.en": extra characters at the end of d command
sed: 1: "data/multi30k/val.en": extra characters at the end of d command
sed: 1: "data/multi30k/train.de": extra characters at the end of d command
sed: 1: "data/multi30k/val.de": extra characters at the end of d command`

Please advice as to how I should proceed

**Comment by sankuniu** [comment]
Thank you for attention! My workbench include ubuntu16.04, pytorch 0.5, python 3.6. But there are errors when I preprocess the data.
sanku@ubuntu:~/apytorch$ for l in en de; do for f in data/multi30k/*.$l; do if [[ "$f" != *"test"* ]]; then sed -i "$ d" $f; fi;  done; done
sanku@ubuntu:~/apytorch$ for l in en de; do for f in data/multi30k/*.$l; do perl tokenizer.perl -a -no-escape -l $l -q  < $f > $f.atok; done; done
Can't open perl script "tokenizer.perl": No such file or directory
Can't open perl script "tokenizer.perl": No such file or directory
Can't open perl script "tokenizer.perl": No such file or directory
Can't open perl script "tokenizer.perl": No such file or directory
Can't open perl script "tokenizer.perl": No such file or directory
Can't open perl script "tokenizer.perl": No such file or directory

**Comment by whikwon** [comment]
@sankuniu having same error
