### ISSUE TITLE
Question about the value of temper in ScaledDotProductAttention and d_inner_hid default value

### ISSUE THREAD

**Issue by zhangdistephen** [jadore801120/attention-is-all-you-need-pytorch#42]
In the origin paper, dot products will be divided by `np.power(d_k, 0.5)`, but in your code, the value, that is temper, is `np.power(d_model, 0.5)`. I guess this may be wrong.

Another question is that in the origin paper, d_inner_hid is 2048, but you define it 1024 as default. I don't know why.

**Comment by jadore801120** [comment]
Hello @zhangdistephen thanks for the notice.
These two issue have been fixed in the newest code  1929a50  .
Please take a look.
Thanks,
Yu-Hsiang
