### ISSUE TITLE
Model training error

### ISSUE THREAD

**Issue by Crista23** [jadore801120/attention-is-all-you-need-pytorch#43]
Training the model throws me the error below:
 
python train.py -data data/multi30k.atok.low.pt -save_model trained -save_mode best -proj_share_weight
Namespace(batch_size=64, cuda=True, d_inner_hid=1024, d_k=64, d_model=512, d_v=64, d_word_vec=512, data='data/multi30k.atok.low.pt', dropout=0.1, embs_share_weight=False, epoch=10, log=None, max_token_seq_len=52, n_head=8, n_layers=6, n_warmup_steps=4000, no_cuda=False, proj_share_weight=True, save_mode='best', save_model='trained', src_vocab_size=2909, tgt_vocab_size=3150)
('[ Epoch', 0, ']')
  - (Training)   :   0%|                                                                                                                                           | 0/453 [00:00<?, ?it/s]/home/user/anaconda2/lib/python2.7/site-packages/torch/nn/modules/module.py:357: UserWarning: Implicit dimension choice for softmax has been deprecated. Change the call to include dim=X as an argument.
  result = self.forward(*input, **kwargs)
Traceback (most recent call last):
  File "train.py", line 271, in <module>
    main()
  File "train.py", line 268, in main
    train(transformer, training_data, validation_data, crit, optimizer, opt)
  File "train.py", line 126, in train
    train_loss, train_accu = train_epoch(model, training_data, crit, optimizer)
  File "train.py", line 57, in train_epoch
    pred = model(src, tgt)
  File "/home/user/anaconda2/lib/python2.7/site-packages/torch/nn/modules/module.py", line 357, in __call__
    result = self.forward(*input, **kwargs)
  File "/srv/disk01/user/medical_data/attention-is-all-you-need-pytorch/transformer/Models.py", line 192, in forward
    enc_output, _ = self.encoder(src_seq, src_pos)
ValueError: need more than 1 value to unpack

**Comment by jadore801120** [comment]
Hello @Crista23 , in here, it is the expected number of return values not equals to the real one.
Have fixed in the newest code, please take a look.
Thanks,
Yu-Hsiang
