### ISSUE TITLE
Code failing while translation

### ISSUE THREAD

**Issue by anuj-rathore** [jadore801120/attention-is-all-you-need-pytorch#46]
For translation, I use the following command
`CUDA_LAUNCH_BLOCKING=1 CUDA_VISIBLE_DEVICES=1 python3 translate.py -model trained.chkpt -vocab data/nmt.atok.low.pt -src data/nmt/test.en.atok`
and get the following error : [error](https://pastebin.com/izrrUwpR)

Can someone help?

**Comment by jadore801120** [comment]
Hello @anuj-rathore , looks like a embedding look up issue.
The code has been updated and shall have no problem now, please take a look.
Thanks,
Yu-Hsiang
