### ISSUE TITLE
Temper in ScaledDotProductAttention?

### ISSUE THREAD

**Issue by ivan-bilan** [jadore801120/attention-is-all-you-need-pytorch#49]
I am referring to this code line that implements temper in ScaledDotProductAttention:
https://github.com/jadore801120/attention-is-all-you-need-pytorch/blob/7fa8c63f9a5a6e997659054ebef2fc1a61630dc2/transformer/Modules.py#L76

What is this value based on? Can someone explain what it does here?

**Comment by wasiahmad** [comment]
It is just computing the square root of `d_model` as suggested in the paper that we should divide the dot product value by the square root of the dimension.

**Comment by cherryyue** [comment]
It seems that in the paper `d_k` is suggested, which is different from the `d_model`. Confused with this.

**Comment by jadore801120** [comment]
@wasiahmad Thanks for explanation.
@cherryyue Thanks for the notice!
