### ISSUE TITLE
About label smoothing.

### ISSUE THREAD

**Issue by chenyangh** [jadore801120/attention-is-all-you-need-pytorch#50]
https://github.com/jadore801120/attention-is-all-you-need-pytorch/blob/7fa8c63f9a5a6e997659054ebef2fc1a61630dc2/train.py#L25

Hi, thanks for the implementation. It is very neat and elegant. I noticed that you mentioned "label smoothing" is not done yet, but I also found you have implemented this line.  I think it is correct but I am not sure what is the num_class in sequence-to-sequence models. Should it be equal to the size of the vocabulary?

**Comment by jadore801120** [comment]
Hello @chenyangh , thanks for your compliment!
Yes, the n_class shall be the vocabulary size but minus 1. (maybe n_rest_class is more accurate)
LSR is to subtract an eps prob from the real label and let the other labels share the subtracted prob. 
The label smoothing part was just completed in fb46df2. Please take a look.
Thanks,
Yu-Hsiang
