### ISSUE TITLE
RunTimeError During Training

### ISSUE THREAD

**Issue by JulianRMedina** [jadore801120/attention-is-all-you-need-pytorch#51]
After training for the first epoch I get the following error trying to calculate training accuracy and loss:

RuntimeError: Expected object of type.cuda.FloatTensor but found type torch.cuda.LongTensor for argument #2 'other

At the following line of code at line 102 in train.py
`return total_loss/n_total_words, n_total_correct/n_total_words`

**Comment by JulianRMedina** [comment]
I was able to fix this with the following:
`return total_loss/n_total_words.float, n_total_correct/n_total_words.float`

**Comment by GeoffNN** [comment]
Fixed for pytorch .4.1 (x5 speedup per iteration by the way) by doing:
`total_loss += loss.item()` in `train_epoch` and `eval_epoch`.

**Comment by jadore801120** [comment]
@JulianRMedina , @GeoffNN Thanks for the observation. It is a version issue. 
The code is update to pytorch 0.4.1, please take a look. Thanks!
