### ISSUE TITLE
Model training error

### ISSUE THREAD

**Issue by ejklektov** [jadore801120/attention-is-all-you-need-pytorch#54]
ejklektov@gpu3:~/attention-is-all-you-need-pytorch$ CUDA_VISIBLE_DEVICES=5 python3 train.py -data data/multi30k.atok.low.pt -save_model trained -save_mode best -proj_share_weight
Namespace(batch_size=64, cuda=True, d_inner_hid=1024, d_k=64, d_model=512, d_v=64, d_word_vec=512, data='data/multi30k.atok.low.pt', dropout=0.1, embs_share_weight=False, epoch=10, log=None, max_token_seq_len=52, n_head=8, n_layers=6, n_warmup_steps=4000, no_cuda=False, proj_share_weight=True, save_mode='best', save_model='trained', src_vocab_size=2909, tgt_vocab_size=3149)
/home/ejklektov/attention-is-all-you-need-pytorch/transformer/Modules.py:13: UserWarning: nn.init.xavier_normal is now deprecated in favor of nn.init.xavier_normal_.
  init.xavier_normal(self.linear.weight)
/home/ejklektov/attention-is-all-you-need-pytorch/transformer/SubLayers.py:33: UserWarning: nn.init.xavier_normal is now deprecated in favor of nn.init.xavier_normal_.
  init.xavier_normal(self.w_qs)
/home/ejklektov/attention-is-all-you-need-pytorch/transformer/SubLayers.py:34: UserWarning: nn.init.xavier_normal is now deprecated in favor of nn.init.xavier_normal_.
  init.xavier_normal(self.w_ks)
/home/ejklektov/attention-is-all-you-need-pytorch/transformer/SubLayers.py:35: UserWarning: nn.init.xavier_normal is now deprecated in favor of nn.init.xavier_normal_.
  init.xavier_normal(self.w_vs)
[ Epoch 0 ]
  - (Training)   :   0%|                                                     | 0/454 [00:00<?, ?it/s]/usr/local/lib/python3.5/dist-packages/torch/nn/modules/module.py:491: UserWarning: Implicit dimension choice for softmax has been deprecated. Change the call to include dim=X as an argument.
  result = self.forward(*input, **kwargs)
train.py:71: UserWarning: invalid index of a 0-dim tensor. This will be an error in PyTorch 0.5. Use tensor.item() to convert a 0-dim tensor to a Python number
  total_loss += loss.data[0]
Traceback (most recent call last):                                                                   
  File "train.py", line 271, in <module>
    main()
  File "train.py", line 268, in main
    train(transformer, training_data, validation_data, crit, optimizer, opt)
  File "train.py", line 126, in train
    train_loss, train_accu = train_epoch(model, training_data, crit, optimizer)
  File "train.py", line 73, in train_epoch
    return total_loss/n_total_words, n_total_correct/n_total_words
RuntimeError: Expected object of type torch.cuda.FloatTensor but found type torch.cuda.LongTensor for argument #2 'other'

**I change train.py 71line code,
loss.data[0] ===> loss.item[0]
but it doesn't work**

**Comment by ejklektov** [comment]
python 3.6
pytorch 0.5 version

**Comment by Xuwanjun9** [comment]
It's loss.item()

**Comment by jadore801120** [comment]
@Xuwanjun9 Thanks for the explanation.
@ejklektov This is a version issue. I have updated the code to pytorch 0.4.1, please take a look.
Thanks,
Yu-Hsiang
