### ISSUE TITLE
eval() questions

### ISSUE THREAD

**Issue by xuefei1** [jadore801120/attention-is-all-you-need-pytorch#55]
In your eval_epoch() function you feedforward src and tgt through the model just like the training phase. Is this correct? Shouldn't eval be similar to testing where the model won't know the true target? Should there be an autoregressive step for evaluation where the prediction words are generated one by one and used by subsequent predictions?

**Comment by yuedongP** [comment]
Hi, I am having the same question. I don't think we are supposed to feed the whole tgt sequence to the model during eval. Your code seems do so though and I think it should be similar to the translate function.

**Comment by jadore801120** [comment]
Hi all, 
Thanks for pointing out.
I think you are correct but for me, it is kind of trade off. 
Using beam search will definitely make the behavior more close to what we do in testing but slow the process?
