### ISSUE TITLE
KeyError on testing

### ISSUE THREAD

**Issue by dksehdals216** [jadore801120/attention-is-all-you-need-pytorch#59]
After fixing a key error about tensor integer types, running translate.py seems to return KeyErrors with numbers, and checking with python seems to indicate that they are missing(the keys).
But skipping keys that are non-existent inside the write loop seems to return poor results.
result of pred.txt after running code
<img width="671" alt="screen shot 2018-08-23 at 3 03 00 pm" src="https://user-images.githubusercontent.com/28642525/44507521-d705c000-a6e5-11e8-979e-e55408519229.png">

heres the changed code:
<img width="671" alt="screen shot 2018-08-23 at 3 03 14 pm" src="https://user-images.githubusercontent.com/28642525/44507532-e258eb80-a6e5-11e8-8c1c-800c00fcef4f.png">

Did anybody experience this or have a fix? Thank you.

**Comment by jadore801120** [comment]
Hello @dksehdals216 , I think it is a pytorch version issue. 
The type of word index I get is a torch tensor object insteat of an integer.
This bug is fixed in the newest code 1929a50. Please have a look.
Thanks,
Yu-Hsiang

**Comment by dksehdals216** [comment]
@jadore801120  Thank you! I was testing with WMT14 but your newer version seems to have fixed it.
