### ISSUE TITLE
Beam search

### ISSUE THREAD

**Issue by charlesfufu** [jadore801120/attention-is-all-you-need-pytorch#63]
In the translate part ,I can't understand how to use beam search in 《attention is you need》.Could you explain it ？

**Comment by jadore801120** [comment]
@charlesfufu 
Please take a look on the newest code. I made it more concise.
If we have beam size as `k`, there will be `k` generated sequence during translation.
We decode it step by step.
At each step, `k` predicted words are selected for each generated sequence. (Hence, we have `k^2` candidates).
We then selected the top `k` sequences from our `k^2` candidates with the consideration of the previous scores (the score is the log form of the production of all the prediction prob of the predicted words in sequence.).
If we reach to EOS token, return the generated sequence with the highest score in `k` candidates.
Hope this helps.
