### ISSUE TITLE
encounter OOM error when the default batch_size is set to a number more than 64, eg 65

### ISSUE THREAD

**Issue by HenryWoodOTC** [jadore801120/attention-is-all-you-need-pytorch#64]
when i set the  the default batch_size 65, i got an OOM error,

1. parameters

Namespace(batch_size=65, cuda=True, d_inner_hid=2048, d_k=64, d_model=512, d_v=64, d_word_vec=512, data='data/wmt.zh-en/wmt.low.pt', dropout=0.1, embs_share_weight=False, epoch=10, label_smoothing=True, log=None, max_token_seq_len=52, n_head=8, n_layers=6, n_warmup_steps=4000, no_cuda=False, proj_share_weight=True, save_mode='best', save_model='trained', src_vocab_size=27572, tgt_vocab_size=18620)

2. error

Traceback (most recent call last):
  File "train.py", line 293, in <module>
    main()
  File "train.py", line 264, in main
    train(transformer, training_data, validation_data, optimizer, device ,opt)
  File "train.py", line 152, in train
    model, training_data, optimizer, device, smoothing=opt.label_smoothing)
  File "train.py", line 77, in train_epoch
    loss, n_correct = cal_performance(pred, gold, smoothing=smoothing)
  File "train.py", line 22, in cal_performance
    loss = cal_loss(pred, gold, smoothing)
  File "train.py", line 43, in cal_loss
    one_hot = one_hot * (1 - eps) + (1 - one_hot) * eps / (n_class - 1)
  File "/home/tensorfly/.conda/envs/pytorch/lib/python3.5/site-packages/torch/tensor.py", line 317, in __rsub__
    return -self + other
RuntimeError: cuda runtime error (2) : out of memory at /pytorch/aten/src/THC/generic/THCStorage.cu:58

**Comment by BinWone** [comment]
+1, the same question. cannot set bigger batch_size, train so slow.

**Comment by jadore801120** [comment]
Please take a look on the newest code.
I try to reduce as many the `contiguous` operations as possible with broadcasting, as well as temp. variables.
But for me, 256 is pretty big for the TITAN X.
If you find some unnecessary memory consuming operations, please tell me or fire a pull request. Thanks.
Hope it helps.
