### ISSUE TITLE
Any reproduced results?

### ISSUE THREAD

**Issue by anoidgit** [jadore801120/attention-is-all-you-need-pytorch#68]
Hi, I have also implemented a [transformer](https://github.com/anoidgit/transformer), but I fail to reproduce the result of Accelerating Neural Transformer via an Average Attention Network even after I enabled beam search and ensemble. There is still a significant gap between my results and the results reported in the paper.

Did you reproduce any result with your implementation? Do you have any advice about the performance gap? There are some people who argue about larger batch size, but I do not think it will result in a such large decrease in BLEU score.

**Comment by qiaopt** [comment]
I have different results from tensor2tensor
