### ISSUE TITLE
MultiHeadAttention() implemention question

### ISSUE THREAD

**Issue by wyjss2015** [jadore801120/attention-is-all-you-need-pytorch#7]
Hi, Yu-Hsiang. 
I am not clear about line 62 in file Sublayers.py
```
# back to original mb_size batch
outputs = outputs.view(mb_size, len_q, -1)            # mb_size x len_q x (n_head*d_v)
```
is it right? 
above code is equal to below(tensorflow implemention from [Kyubyong](https://github.com/Kyubyong/transformer/blob/master/modules.py))?
```
# Restore shape
outputs = tf.concat(tf.split(outputs, num_heads, axis=0), axis=2 )          # (N, T_q, C)
```

**Comment by jadore801120** [comment]
Hi @wyjss2015 ,
Thanks for point out!
This error has been fixed in [ca8c7c0](https://github.com/jadore801120/attention-is-all-you-need-pytorch/commit/ca8c7c0ad5a807398a998eb1889f92813c5864f3).
