### ISSUE TITLE
I think the best_score_and_idx should be scores[0] and ids[0]. Why is the index 1 here? 

### ISSUE THREAD

**Issue by JepsonWong** [jadore801120/attention-is-all-you-need-pytorch#73]
https://github.com/jadore801120/attention-is-all-you-need-pytorch/blob/20f355eb655bad40195ae302b9d8036716be9a23/transformer/Beam.py#L81

**Comment by jadore801120** [comment]
Sorry for the confusion. Please take a look on the newest code.
Best,
Yu-Hsiang
