### ISSUE TITLE
translate so slow, a batch composed of 64 instances will cost 13s+ to translate?

### ISSUE THREAD

**Issue by BinWone** [jadore801120/attention-is-all-you-need-pytorch#74]
I found that beam_decode_step will cost 8s+, it's the most time consuming step. Is there any place to optimize?

**Comment by huangnengCSU** [comment]
I meet the same problem, the translation is very slow.

**Comment by jadore801120** [comment]
Hello @BinWone and @huangnengCSU Thanks for pointing out!
Please take a look on the newest code.
Although in the new version, the code only support translating sentence by sentences, I make it more concise and avoid using for loop as possible as i can.
Hope it helps. Thanks.
