### ISSUE TITLE
Why in Beam needs 2 time topk operation?

### ISSUE THREAD

**Issue by Genie-Liu** [jadore801120/attention-is-all-you-need-pytorch#75]
This 2 operations have the same result, why we need 2 same line here?

https://github.com/jadore801120/attention-is-all-you-need-pytorch/blob/20f355eb655bad40195ae302b9d8036716be9a23/transformer/Beam.py#L55-L56

**Comment by MFajcik** [comment]
That makes no sense to me either...

**Comment by Frozenmad** [comment]
I think the discussion in issue #1 helps explain this problem (in the last two answers).

**Comment by jadore801120** [comment]
@Frozenmad That's correct, thanks for pointing out!
With the newer version of pytorch, it is no longer needed.
Sorry for the confusion.
