### ISSUE TITLE
the reason why translate runs so slowly.

### ISSUE THREAD

**Issue by huangnengCSU** [jadore801120/attention-is-all-you-need-pytorch#77]
when doing beam search,at each step we need to know the previous best path, and then concatenate the current prediction to make the new target input. In the code, to know the previous path, it calls get_current_state() in Beam.py. This function will track back to get the previous best path. If the decode path is N, then the function will be call N times. It cost too much time. We just need a array to storage previous best path and update them, instead of backtracking.

**Comment by noowad** [comment]
it may be helpful to refer to the most recently updated fairseq beam search code.
https://github.com/pytorch/fairseq/blob/master/fairseq/search.py

**Comment by jadore801120** [comment]
Please check the newest code.
Hope this helps
