### ISSUE TITLE
Question about beamsearch

### ISSUE THREAD

**Issue by ZhengkunTian** [jadore801120/attention-is-all-you-need-pytorch#79]
hello，
       Your code is very clear! However, I have a quesion about beam search in your code.  Why did you do two sorting operations in transformer/beam.py? Is there any special purpose? 
![image](https://user-images.githubusercontent.com/27281510/50480257-d1164780-0a15-11e9-8591-14e237c8ed6f.png)
 Thanks a lot!

**Comment by benbijituo** [comment]
I am also confused.Have you got an explanation?
It's seems reasonable cuz the annotation there.
@ZhengkunTian @jadore801120

**Comment by jadore801120** [comment]
I am sorry about the confusion.
It was a bug in the pytorch version I used in the beginning.
At that version, `topk` sometimes returned buggy result, but it always returned correct result at the second call.
So it is just a work-around, and it is no need to do that now.
Hope it helps.
