### ISSUE TITLE
Is this really multiheaded attention?

### ISSUE THREAD

**Issue by giannisdaras** [jadore801120/attention-is-all-you-need-pytorch#80]
Hello, congratulations for your implementation.
I have a question about the multiheaded attention, specifically regarding this piece of code:
```
        output, attn = self.attention(q, k, v, mask=mask)
        output = output.view(n_head, sz_b, len_q, d_v)
        output = output.permute(1, 2, 0, 3).contiguous().view(sz_b, len_q, -1) # b x lq x (n*dv)
        output = self.dropout(self.fc(output))
        output = self.layer_norm(output + residual)
```

As far as I understand, you are using one head attention, then using view to get the multiple heads and then project back to one head. I can't figure out why this is actually multiheaded attention. It's like you are reverting the first view with the second one. 

I think that it would be right to project to the multiple heads before calling the ScaledDotProductAttention function. That would truly give multiple heads, which you could merge into one with a linear multiplication.

Please shed some light on this in case I am wrong.

**Comment by elvisyjlin** [comment]
I think it's actually a multi-head self-attention here.

The key point here is [`torch.bmm()`](https://pytorch.org/docs/stable/torch.html#torch.bmm) in [`ScaledDotProductAttention()`](https://github.com/jadore801120/attention-is-all-you-need-pytorch/blob/master/transformer/Modules.py#L18). `torch.bmm()` is a matrix-matrix product of matrices, which performs batchwise matrix multiplication. For example, `c = torch.bmm(a, b)` outputs a `c` in the size of (b, n, p) if `a` is a (b, n, m) tensor and `b` is a (b, m, p) tensor.

In [the first line](https://github.com/jadore801120/attention-is-all-you-need-pytorch/blob/2077515a8ab24f4abdda9089c502fa14f32fc5d9/transformer/SubLayers.py#L54) of the code you mentioned, 
```python
output, attn = self.attention(q, k, v, mask=mask)
```
`q`, `k`, and `v` here are already projected into multi-head with the size of (n_head * batch, len, dim). The `q` and `k` are then computed into attention _per batch and per head_ (via `torch.bmm()`). You can also consider them as if there are (n_head * batch) sentences to be calculated their self-attention. And they will be merged (projected) back to each sentence in [the last three lines](https://github.com/jadore801120/attention-is-all-you-need-pytorch/blob/2077515a8ab24f4abdda9089c502fa14f32fc5d9/transformer/SubLayers.py#L58) of the code.
```python
output = output.permute(1, 2, 0, 3).contiguous().view(sz_b, len_q, -1) # b x lq x (n*dv)
output = self.dropout(self.fc(output))
output = self.layer_norm(output + residual)
```

**Comment by jadore801120** [comment]
@elvisyjlin Thanks for your detailed explanation!
@giannisdaras I think the newest code make it much clear.
If you don't mind, please take a look.
https://github.com/jadore801120/attention-is-all-you-need-pytorch/blob/master/transformer/SubLayers.py#L38-L54
Hope it helps.
