### ISSUE TITLE
Did you use LSTM or GRU in the encoder and attention part?

### ISSUE THREAD

**Issue by liperrino** [jadore801120/attention-is-all-you-need-pytorch#81]
Did you use LSTM or GRU in the encoder and decoder?
I have tried to read your code to look if it is the case but i did not see anything like that. Please i would like to add it in the encoder and attention part. please tell me how i can do it.

**Comment by ivan-bilan** [comment]
@liperrino the whole point of the original paper was that you don't use any form of RNNs in the Transformer, why would you need to add it anywhere? The transformer is non-sequential, it compares every word in the sentence to every other word in the sentence and the sequence of the words is represented through the positional encodings, there is no point in using RNNs anywhere.

**Comment by liperrino** [comment]
@ivan-bilan  Ok, thanks very much for your explanations
