### ISSUE TITLE
arguments problem?

### ISSUE THREAD

**Issue by A6Matrix** [jadore801120/attention-is-all-you-need-pytorch#82]
These errors occur when I run the preprocess.py and train.py
![image](https://user-images.githubusercontent.com/18898570/51308792-ebc06700-1a7d-11e9-94be-592bfa6c1280.png)
![image](https://user-images.githubusercontent.com/18898570/51308811-f549cf00-1a7d-11e9-9fbc-0c086c0c787d.png)

**Comment by elvisyjlin** [comment]
I did not encounter any error when preprocessing data and training the model.
@A6Matrix Could you please provide what commands you typed for running `preprocess.py` and `train.py`?

**Comment by A6Matrix** [comment]
> I did not encounter any error when preprocessing data and training the model.
> @A6Matrix Could you please provide what commands you typed for running `preprocess.py` and `train.py`?

first step：download data，the command i wrote is ‘mkdir -p data/multi30k’。
![image](https://user-images.githubusercontent.com/18898570/51439972-32bb9000-1cfc-11e9-9c93-f2ce876ea863.png)
so I created the folder manually
![image](https://user-images.githubusercontent.com/18898570/51439987-64345b80-1cfc-11e9-9b59-f20016332830.png)

second step：i write command like this，but there are errors.
![image](https://user-images.githubusercontent.com/18898570/51439999-95ad2700-1cfc-11e9-8b99-63881f198c65.png)

third step：i write command like this，it says cannot found tqdm module，but i have installed 
![image](https://user-images.githubusercontent.com/18898570/51440052-79f65080-1cfd-11e9-8dd2-f59f950ce82d.png)
![image](https://user-images.githubusercontent.com/18898570/51440071-bc1f9200-1cfd-11e9-97d3-f703118d06be.png)

Can you help me with these problems，i'm just starting to learn pytorch，thank you very  much

**Comment by elvisyjlin** [comment]
### In the First Step

You must have run the code in Windows, instead of Linux or MacOS. The commands are different between _bash_ in Linux or MacOS and _Command shell_ in Windows. In Windows, the command should be:
```bash
mkdir data\multi30k
```

Anyway, you've created the directory. Then you can [download the data](https://github.com/jadore801120/attention-is-all-you-need-pytorch#0-download-the-data).

Now, you should have these files under `data/multi30k`.

```text
data
└── multi30k
    ├── train.en
    ├── train.de
    ├── val.en
    ├── val.de
    ├── test.en
    └── test.de
```

Then you need Perl (https://www.perl.org/get.html) and run the follow two commands:
```bash
for l in en de; do for f in data/multi30k/*.$l; do if [[ "$f" != *"test"* ]]; then sed -i "$ d" $f; fi;  done; done
for l in en de; do for f in data/multi30k/*.$l; do perl tokenizer.perl -a -no-escape -l $l -q  < $f > $f.atok; done; done
```

And you will have these files after you preprocess with the Perl scripts:

```text
data
└── multi30k
    ├── train.en
    ├── train.de
    ├── val.en
    ├── val.de
    ├── test.en
    ├── test.de
    ├── train.en.atok
    ├── train.de.atok
    ├── val.en.atok
    ├── val.de.atok
    ├── test.en.atok
    └── test.de.atok
```

### In the Second Step

The error indicates that data `data/multi30k/train.en.atok` was not found. If you follow the aforementioned instructions, you should be able to run `preprocess.py`.

```bash
python preprocess.py -train_src data/multi30k/train.en.atok -train_tgt data/multi30k/train.de.atok -valid_src data/multi30k/val.en.atok -valid_tgt data/multi30k/val.de.atok -save_data data/multi30k.atok.low.pt
```

### In the Third Step

Can you run the command and check if tqdm exists?

```bash
pip list
```

Or are you using `virtual-env`? I saw there is a `(tensorflow)` in your last screenshot. You probably forgot to run `train.py` under this setting because there is no `(tensorflow)` at the beginning of `C:\Users\blablabla...`.

**Comment by elvisyjlin** [comment]
The commands (for loop, `sed`, etc.) in _the first step_ are also for Linux bash. I'm sorry about that. I currently have no idea about how to do it under Windows Command shell. Please try to install bash and then run the commands in bash.
https://www.windowscentral.com/how-install-bash-shell-command-line-windows-10

If you are able to do run it in a Linux system (e.g. Ubuntu). Everything should work fine.

**Comment by A6Matrix** [comment]
> The commands (for loop, `sed`, etc.) in _the first step_ are also for Linux bash. I'm sorry about that. I currently have no idea about how to do it under Windows Command shell. Please try to install bash and then run the commands in bash.
> https://www.windowscentral.com/how-install-bash-shell-command-line-windows-10
> 
> If you are able to do run it in a Linux system (e.g. Ubuntu). Everything should work fine.

Could you please send these documents to me directly? I will try to see if it is ok
![image](https://user-images.githubusercontent.com/18898570/51458200-54b22280-1d8f-11e9-9455-c3f10b358159.png)

**Comment by elvisyjlin** [comment]
Sure. Here is my `multi30k`: https://drive.google.com/open?id=1iWktY9kM7cCcLMCjg9nPLe6wJCgHKlrl

**Comment by A6Matrix** [comment]
> Sure. Here is my `multi30k`: https://drive.google.com/open?id=1iWktY9kM7cCcLMCjg9nPLe6wJCgHKlrl

![image](https://user-images.githubusercontent.com/18898570/51478657-002a9980-1dc7-11e9-8ead-f8cb98d76b4a.png)
why is that?

**Comment by elvisyjlin** [comment]
The reason is that your default system encoding is not UTF-8. I've opened a [pull request](https://github.com/jadore801120/attention-is-all-you-need-pytorch/pull/83) to resolve it. Please revise your `preprocess.py` and `translate.py` according to [the revisions](https://github.com/jadore801120/attention-is-all-you-need-pytorch/pull/83/commits/6276e01fcb6f628fab997ea9ba281c3ca244e251).

**Comment by A6Matrix** [comment]
> The reason is that your default system encoding is not UTF-8. I've opened a [pull request](https://github.com/jadore801120/attention-is-all-you-need-pytorch/pull/83) to resolve it. Please revise your `preprocess.py` and `translate.py` according to [the revisions](https://github.com/jadore801120/attention-is-all-you-need-pytorch/pull/83/commits/6276e01fcb6f628fab997ea9ba281c3ca244e251).

OK，I run the preprocess.py and have the results
![image](https://user-images.githubusercontent.com/18898570/51521054-5f88b800-1e60-11e9-853c-2f533abd042e.png)

I don't have a GPU version of the pytorch on my laptop，but doesn't this code run on the CPU version as well? ` device = torch.device('cuda' if opt.cuda else 'cpu')` ，What code comments do I need?
![image](https://user-images.githubusercontent.com/18898570/51521078-716a5b00-1e60-11e9-9c44-daaf697eaeb5.png)
I really appreciate that you are so kind to answer my questions

**Comment by elvisyjlin** [comment]
Yes, you can run the code without GPU. Just specify `-no_cuda` in arguments like the one in [readme](https://github.com/jadore801120/attention-is-all-you-need-pytorch#3-test-the-model).

For example, 
```bash
python train.py -data data/multi30k.atok.low.pt -save_model trained -save_mode best -proj_share_weight -label_smoothing -no_cuda
```

**Comment by A6Matrix** [comment]
> Yes, you can run the code without GPU. Just specify `-no_cuda` in arguments like the one in [readme](https://github.com/jadore801120/attention-is-all-you-need-pytorch#3-test-the-model).
> 
> For example,
> 
> ```shell
> python train.py -data data/multi30k.atok.low.pt -save_model trained -save_mode best -proj_share_weight -label_smoothing -no_cuda
> ```
i replace this code `opt.cuda = not opt.no_cuda` with `opt.cuda = opt.no_cuda`，and it also runs
![image](https://user-images.githubusercontent.com/18898570/51524036-13417600-1e68-11e9-88bd-638d19ac1b7c.png)
thank you very much，Can I still ask you about the code

**Comment by elvisyjlin** [comment]
Sure. But the issue should be closed because the problem was solved, I think. You can email me if you have any other question about the code.

**Comment by A6Matrix** [comment]
> Sure. But the issue should be closed because the problem was solved, I think. You can email me if you have any other question about the code.

ok
