### ISSUE TITLE
How to use multi-GPUS ?

### ISSUE THREAD

**Issue by neu-teng** [jadore801120/attention-is-all-you-need-pytorch#84]
Hi ,  I tried to do experiments on my data with the code 
The amount is about 3 billion per language between Chinese and Japanese.
If i train the model on the single gpu it will costs about 21 hours per epoch.
So if any one know how to change the model to fit multi-gpus training?
And finally , thanks for sharing the code.

**Comment by KAISER1997** [comment]
hi, did you find a way to use multi-gpus training?

**Comment by huangxianliang** [comment]
hi,i have the same problem,can any one help us? thks
