### ISSUE TITLE
Maybe there should be a NoneType check in transformer.SubLayers line 53

### ISSUE THREAD

**Issue by Ylizin** [jadore801120/attention-is-all-you-need-pytorch#91]
When i used the encoderLayer respectively and without passing a mask to it, it came out an attributeError in mask.repeat. So i wonder if it is necessary to check if mask is NoneType here in transformer/SubLayers line 53 in the master brach.
:-)

**Comment by jadore801120** [comment]
@Ylizin 
Thanks for pointing out! You are right.
In the newest code, there is no this kind of issue. 
Please take a look. Thanks!
