### ISSUE TITLE
GPU transition problem

### ISSUE THREAD

**Issue by HikaruSama233** [jadore801120/attention-is-all-you-need-pytorch#95]
https://github.com/jadore801120/attention-is-all-you-need-pytorch/blob/20f355eb655bad40195ae302b9d8036716be9a23/transformer/Translator.py#L17

this line should be 

`checkpoint = torch.load(opt.model, map_location=self.device)`

Otherwise when the GPU that was used to train the model is full, the system will raise an error "cuda out of memory" no matter you use GPU or CPU

**Comment by jadore801120** [comment]
@HikaruSama233 Thanks for pointing out!
I have modified it in the newest code.
Thanks!
