### ISSUE TITLE
Translate sentence by sentence

### ISSUE THREAD

**Issue by nikhiljaiswal** [jadore801120/attention-is-all-you-need-pytorch#98]
Can I load the model once and give as input a single sentence and accordingly get the response and repeat the process?

**Comment by colllin** [comment]
Why not?  Assuming you have a trained model to load.  Did you try it?

**Comment by jadore801120** [comment]
@nikhiljaiswal 
It could be done now (and can only be done in this style).
Please take a look on the newest code. Thanks!
Hope this helps.
