### ISSUE TITLE
Meaning of `padding_idx` in `get_sinusoid_encoding_table`?

### ISSUE THREAD

**Issue by colllin** [jadore801120/attention-is-all-you-need-pytorch#99]
Hi 👋 

Thank you for this repository.  I noticed that `padding_idx` appears to be hard-coded in these lines, and in my project I have some special handling around padding, But I’m having a hard time following exactly what is happening here.  Is it intended that `padding_idx` is hard-coded to `0`?  Or should it be set to `Constants.PAD`?  How should I decide what to set this value to?  It appears to set the 0th embedding index to zeros...  then it also looks like the positional encoding is similar to `list(range(1, max_seq_len+1))`... which I’m guessing is then filled with `Constants.PAD` at positions outside the src/tgt sequence?  Does that sound right?  So then it really should be set as `padding_idx=Constants.PAD`?

https://github.com/jadore801120/attention-is-all-you-need-pytorch/blob/20f355eb655bad40195ae302b9d8036716be9a23/transformer/Models.py#L71
https://github.com/jadore801120/attention-is-all-you-need-pytorch/blob/20f355eb655bad40195ae302b9d8036716be9a23/transformer/Models.py#L117

**Comment by HedyHu** [comment]
Same question here. I think the padding_idx should be the position of the last word in one sentence. The current syntax makes the first position to be all zeros. I recommend padding_idx to be an array of all the real sentence lengths.

**Comment by Jordan-5i** [comment]
I think padding_idx=0 is the purpose of letting PAD positions of sentences equal to zeros, because the PAD positions have no efftect. The PAD positions are always encoded to zeros.
https://github.com/jadore801120/attention-is-all-you-need-pytorch/blob/20f355eb655bad40195ae302b9d8036716be9a23/dataset.py#L22

**Comment by jadore801120** [comment]
Hi all, I think it is actually useless, so I remove it now. 
Thanks for point out!
